public enum ACTOR_TYPE
{
    WORKER, SOLDIER, GUNNER, SCORPION, GOBBER, ZOMBIE, BLOB, SPIKES, TURRET
}

public enum STATE
{
    IDLE, GOTO, BUILD, CARRYING, LOADING, UNLOADING, FOLLOWING, ATTACK, DEAD, PATROL, DIG
}